export const CREATE_FEEDBACK_REQUESTED = 'CREATE_FEEDBACK_REQUESTED' as const;
export const CREATE_FEEDBACK_SUCCEEDED = 'CREATE_FEEDBACK_SUCCEEDED' as const;
export const CREATE_FEEDBACK_FAILED = 'CREATE_FEEDBACK_FAILED' as const;

export const UPDATE_FEEDBACK_REQUESTED = 'UPDATE_FEEDBACK_REQUESTED' as const;
export const UPDATE_FEEDBACK_SUCCEEDED = 'UPDATE_FEEDBACK_SUCCEEDED' as const;
export const UPDATE_FEEDBACK_FAILED = 'UPDATE_FEEDBACK_FAILED' as const;

export const DELETE_FEEDBACK_REQUESTED = 'DELETE_FEEDBACK_REQUESTED' as const;
export const DELETE_FEEDBACK_SUCCEEDED = 'DELETE_FEEDBACK_SUCCEEDED' as const;
export const DELETE_FEEDBACK_FAILED = 'DELETE_FEEDBACK_FAILED' as const;

export const GET_FEEDBACK_REQUESTED = 'GET_FEEDBACK_REQUESTED' as const;
export const GET_FEEDBACK_SUCCEEDED = 'GET_FEEDBACK_SUCCEEDED' as const;
export const GET_FEEDBACK_FAILED = 'GET_FEEDBACK_FAILED' as const;

export const RESET_FEEDBACK = 'RESET_FEEDBACK' as const;
